# Travis CI documentation https://docs.travis-ci.com/
 
language: csharp  
os:  
  - linux
  - osx

# .NET CLI require Ubuntu 14.04
sudo: required  
dist: trusty  
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

# .NET CLI require OSX 10.10
osx_image: xcode7.1  

# https://docs.travis-ci.com/user/languages/csharp/
matrix:
  include:
    # Ensure that .NET Core is installed
    - dotnet: 1.0.0-preview2-003121
      mono: none
    # Ensure Mono is installed
    - mono: latest

env:  
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

# Cache the following directories between builds to speed them up
cache:
  directories:
    - tools

# You must run the following command for Travis to be able to have permissions to execute the shell script below. 
# git update-index --chmod=+x build.sh
script:  
  - ./build.sh