# Travis CI documentation https://docs.travis-ci.com/
 
language: csharp  
os:  
  - linux
  - osx

# .NET CLI require Ubuntu 14.04
sudo: required  
dist: trusty  
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

# .NET CLI require OSX 10.10
osx_image: xcode7.1  
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

# Ensure Mono is installed
mono:  
  - 4.4.2

# Install the /NET CLI
env:  
  - CLI_VERSION=latest
install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

# Cache the following directories between builds to speed them up
cache:
  directories:
    - tools

# You must run the following command for Travis to be able to have permissions to execute the shell script below. 
# git update-index --chmod=+x build.sh
script:  
  - ./build.sh